#!/bin/sh

rm -r /tmp/xscreenshot-cache/statusmagic
git clone https://github.com/shinydevelopment/SimulatorStatusMagic /tmp/xscreenshot-cache/statusmagic

xscreenshot --magic "/tmp/xscreenshot-cache/statusmagic" $@